---
opsman-configuration:
  azure:
    tenant_id: ((tenant_id))
    subscription_id: ((subscription_id))
    client_id: ((client_id))
    client_secret: ((client_secret))
    location: ((location))
    resource_group: ((pcf_resource_group_name))
    storage_account: ((ops_manager_storage_account))   # account name of container
    ssh_public_key: ((ops_manager_ssh_public_key))  # ssh key to access VM

    # Note that there are several environment-specific details in this path
    # This path can reach out to other resource groups if necessary
    subnet_id: /subscriptions/((subscription_id))/resourceGroups/((pcf_resource_group_name))/providers/Microsoft.Network/virtualNetworks/((network_name))/subnets/((infrastructure_subnet_name))

    # At least one IP address (public or private) needs to be assigned
    # to the VM. It is also permissible to assign both.
    private_ip: ((ops_manager_private_ip))
    public_ip: ((ops_manager_public_ip))

    # storage_key: ((storage-key))    # only required if your client does not
                                      # have the needed storage permissions
    # container: opsmanagerimage      # storage account container name
                                      # default - opsmanagerimage
    network_security_group: ((ops_manager_security_group_name))
    # vm_name: ops-manager-vm         # default - ops-manager-vm
    # boot_disk_size: 200             # default - 200 (GB)
    # use_managed_disk: true          # this flag is only respected by the
                                      # create-vm and upgrade-opsman commands.
                                      # set to false if you want to create
                                      # the new opsman VM with an unmanaged
                                      # disk (not recommended). default - true
    storage_sku: Premium_LRS        # this sets the SKU of the storage account
                                      # for the disk
                                      # Allowed values: Standard_LRS, Premium_LRS,
                                      # StandardSSD_LRS, UltraSSD_LRS
    # vm_size: Standard_DS1_v2        # the size of the Ops Manager VM
                                      # default - Standard_DS2_v2
                                      # Allowed values: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general