product-name: cf
network-properties:
  network:
    name: pas
  service_network:
    name: services
  other_availability_zones:
  - name: ((availability_zones.0))
  - name: ((availability_zones.1))
  - name: ((availability_zones.2))
  singleton_availability_zone:
    name: ((availability_zones.0))
product-properties:
  .cloud_controller.apps_domain:
    value: ((apps_dns_domain))
  .cloud_controller.system_domain:
    value: ((sys_dns_domain))
  .properties.cf_networking_search_domains:
    value: apps.internal
  .ha_proxy.skip_cert_verify:
    value: true
  .mysql_monitor.recipient_email:
    value: cf-infra@pivotal.io
  .properties.credhub_internal_provider_keys:
    value:
    - key:
        secret: 1a2b3c4d5e6f7g8h9i0j
      name: Key
      primary: true
  .properties.haproxy_forward_tls:
    value: disable
  .properties.networking_poe_ssl_certs:
    value:
    - certificate:
        cert_pem: |
          ((ssl_certificate))
        private_key_pem: |
          ((ssl_private_key))
      name: Certificate
  .properties.security_acknowledgement:
    value: X
  .properties.system_blobstore:
    value: external
  .properties.system_blobstore.external.endpoint:
    value: https://s3-((region)).amazonaws.com
  .properties.system_blobstore.external.access_key:
    value: ((ops_manager_iam_user_access_key))
  .properties.system_blobstore.external.secret_key:
    value:
      secret: "((ops_manager_iam_user_secret_key))"
  .properties.system_blobstore.external.signature_version:
    value: 4
  .properties.system_blobstore.external.region:
    value: ((region))
  .properties.system_blobstore.external.buildpacks_bucket:
    value: ((buildpacks_bucket_name))
  .properties.system_blobstore.external.droplets_bucket:
    value: ((droplets_bucket_name))
  .properties.system_blobstore.external.packages_bucket:
    value: ((packages_bucket_name))
  .properties.system_blobstore.external.resources_bucket:
    value: ((resources_bucket_name))
  .properties.system_blobstore.external.versioning:
    value: 1
  .properties.tcp_routing:
    value: enable
  .properties.tcp_routing.enable.reservable_ports:
    value: 1024-1033
  .uaa.service_provider_key_credentials:
    value:
      cert_pem: |
        ((ssl_certificate))
      private_key_pem: |
        ((ssl_private_key))
  .properties.metric_registrar_blacklisted_tags:
    value: deployment,job,index
resource-config:
  compute:
    instances: 1
    instance_type:
      id: automatic
  control:
    instances: 1
    instance_type:
      id: r5.xlarge
    elb_names:
    - alb:((ssh_target_group_name))
    additional_vm_extensions:
    - ssh-lb-security-groups
  database:
    instances: 1
    instance_type:
      id: m5.large
  router:
    instances: 1
    instance_type:
      id: c5.large
    elb_names:
    - alb:((web_target_group_names.0))
    - alb:((web_target_group_names.1))
    additional_vm_extensions:
    - web-lb-security-groups
  tcp_router:
    instances: 1
    instance_type:
      id: t3.micro
    elb_names:
    - alb:((tcp_target_group_names.0))
    - alb:((tcp_target_group_names.1))
    - alb:((tcp_target_group_names.2))
    - alb:((tcp_target_group_names.3))
    - alb:((tcp_target_group_names.4))
    additional_vm_extensions:
    - tcp-lb-security-groups
  ha_proxy:
    instances: 0
  blobstore:
    instances: 0
  backup_restore:
    instances: 0