product-name: appMetrics
product-properties:
  .db-and-errand-runner.enable_logs:
    value: true
  .db-and-errand-runner.use_socks_proxy:
    value: false
  .log-store-vms.log_store_prune_interval:
    value: 2m
  .log-store-vms.log_store_prune_threshold:
    value: 80
network-properties:
  network:
    name: pas
  other_availability_zones:
  - name: zone-1
  - name: zone-2
  - name: zone-3
  singleton_availability_zone:
    name: zone-3
resource-config:
  db-and-errand-runner:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: Standard_F2s_v2
    instances: automatic
    internet_connected: false
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  log-store-vms:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: Standard_F2s_v2
    instances: automatic
    internet_connected: false
    persistent_disk:
      size_mb: "20480"
    swap_as_percent_of_memory_size: automatic
errand-config:
  delete-space:
    pre-delete-state: true
  migrate-route:
    post-deploy-state: false
  push-app-metrics:
    post-deploy-state: true
  smoke-test:
    post-deploy-state: true
syslog-properties:
  address: logstash.maki.lol
  custom_rsyslog_configuration: null
  enabled: true
  forward_debug_logs: false
  permitted_peer: null
  port: 5518
  queue_size: null
  ssl_ca_certificate: null
  tls_enabled: false
  transport_protocol: tcp

