product-name: metric-store
network-properties:
  network:
    name: pas
  other_availability_zones:
  - name: zone-1
  - name: zone-2
  - name: zone-3
  singleton_availability_zone:
    name: zone-3
resource-config:
  metric-store:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: false
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
errand-config:
  metric-store-smoke-tests:
    post-deploy-state: true
syslog-properties:
  address: null
  custom_rsyslog_configuration: null
  enabled: false
  forward_debug_logs: false
  permitted_peer: null
  port: null
  queue_size: null
  ssl_ca_certificate: null
  tls_enabled: false
  transport_protocol: tcp

