---
az-configuration:
- name: ((availability_zones.0))
- name: ((availability_zones.1))
- name: ((availability_zones.2))
network-assignment:
  network:
    name: management
  singleton_availability_zone:
    name: ((availability_zones.0))
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: management
    subnets:
    - availability_zone_names:
      - ((availability_zones.0))
      cidr: ((management_subnet_cidrs.0))
      dns: 169.254.169.253
      gateway: ((management_subnet_gateways.0))
      iaas_identifier: ((management_subnet_ids.0))
      reserved_ip_ranges: ((management_subnet_reserved_ip_ranges.0))
    - availability_zone_names:
      - ((availability_zones.1))
      cidr: ((management_subnet_cidrs.1))
      dns: 169.254.169.253
      gateway: ((management_subnet_gateways.1))
      iaas_identifier: ((management_subnet_ids.1))
      reserved_ip_ranges: ((management_subnet_reserved_ip_ranges.1))
    - availability_zone_names:
      - ((availability_zones.2))
      cidr: ((management_subnet_cidrs.2))
      dns: 169.254.169.253
      gateway: ((management_subnet_gateways.2))
      iaas_identifier: ((management_subnet_ids.2))
      reserved_ip_ranges: ((management_subnet_reserved_ip_ranges.2))
  - name: pas
    subnets:
    - availability_zone_names:
      - ((availability_zones.0))
      cidr: ((pas_subnet_cidrs.0))
      dns: 169.254.169.253
      gateway: ((pas_subnet_gateways.0))
      iaas_identifier: ((pas_subnet_ids.0))
      reserved_ip_ranges: ((pas_subnet_reserved_ip_ranges.0))
    - availability_zone_names:
      - ((availability_zones.1))
      cidr: ((pas_subnet_cidrs.1))
      dns: 169.254.169.253
      gateway: ((pas_subnet_gateways.1))
      iaas_identifier: ((pas_subnet_ids.1))
      reserved_ip_ranges: ((pas_subnet_reserved_ip_ranges.1))
    - availability_zone_names:
      - ((availability_zones.2))
      cidr: ((pas_subnet_cidrs.2))
      dns: 169.254.169.253
      gateway: ((pas_subnet_gateways.2))
      iaas_identifier: ((pas_subnet_ids.2))
      reserved_ip_ranges: ((pas_subnet_reserved_ip_ranges.2))
  - name: pks
    subnets:
    - availability_zone_names:
      - ((availability_zones.0))
      cidr: ((pks_subnet_cidrs.0))
      dns: 169.254.169.253
      gateway: ((pks_subnet_gateways.0))
      iaas_identifier: ((pks_subnet_ids.0))
      reserved_ip_ranges: ((pks_subnet_reserved_ip_ranges.0))
    - availability_zone_names:
      - ((availability_zones.1))
      cidr: ((pks_subnet_cidrs.1))
      dns: 169.254.169.253
      gateway: ((pks_subnet_gateways.1))
      iaas_identifier: ((pks_subnet_ids.1))
      reserved_ip_ranges: ((pks_subnet_reserved_ip_ranges.1))
    - availability_zone_names:
      - ((availability_zones.2))
      cidr: ((pks_subnet_cidrs.2))
      dns: 169.254.169.253
      gateway: ((pks_subnet_gateways.2))
      iaas_identifier: ((pks_subnet_ids.2))
      reserved_ip_ranges: ((pks_subnet_reserved_ip_ranges.2))
  - name: services
    subnets:
    - availability_zone_names:
      - ((availability_zones.0))
      cidr: ((services_subnet_cidrs.0))
      dns: 169.254.169.253
      gateway: ((services_subnet_gateways.0))
      iaas_identifier: ((services_subnet_ids.0))
      reserved_ip_ranges: ((services_subnet_reserved_ip_ranges.0))
    - availability_zone_names:
      - ((availability_zones.1))
      cidr: ((services_subnet_cidrs.1))
      dns: 169.254.169.253
      gateway: ((services_subnet_gateways.1))
      iaas_identifier: ((services_subnet_ids.1))
      reserved_ip_ranges: ((services_subnet_reserved_ip_ranges.1))
    - availability_zone_names:
      - ((availability_zones.2))
      cidr: ((services_subnet_cidrs.2))
      dns: 169.254.169.253
      gateway: ((services_subnet_gateways.2))
      iaas_identifier: ((services_subnet_ids.2))
      reserved_ip_ranges: ((services_subnet_reserved_ip_ranges.2))
properties-configuration:
  director_configuration:
    ntp_servers_string: 0.amazon.pool.ntp.org, 1.amazon.pool.ntp.org, 2.amazon.pool.ntp.org, 3.amazon.pool.ntp.org
    post_deploy_enabled: true
    resurrector_enabled: true
    blobstore_type: s3
    s3_blobstore_options:
      endpoint: https://s3-((region)).amazonaws.com
      bucket_name: ((ops_manager_bucket))
      access_key: ((ops_manager_iam_user_access_key))
      secret_key: ((ops_manager_iam_user_secret_key))
      signature_version: "4"
      region: ((region))
      backup_strategy: use_versioned_bucket
  iaas_configuration:
    access_key_id: ((ops_manager_iam_user_access_key))
    secret_access_key: ((ops_manager_iam_user_secret_key))
    iam_instance_profile: ((ops_manager_iam_instance_profile_name))
    vpc_id: ((vpc_id))
    security_group: ((platform_vms_security_group_id))
    key_pair_name: ((ops_manager_key_pair_name))
    ssh_private_key: ((ops_manager_ssh_private_key))
    region: ((region))
  security_configuration:
    opsmanager_root_ca_trusted_certs: true
resource-configuration:
  compilation:
    instance_type:
      id: automatic
vmextensions-configuration:
- name: web-lb-security-groups
  cloud_properties:
    security_groups:
    - ((web_lb_security_group_id))
    - ((platform_vms_security_group_id))
- name: ssh-lb-security-groups
  cloud_properties:
    security_groups:
    - ((ssh_lb_security_group_id))
    - ((platform_vms_security_group_id))
- name: tcp-lb-security-groups
  cloud_properties:
    security_groups:
    - ((tcp_lb_security_group_id))
    - ((platform_vms_security_group_id))
- name: tas-blobstore-iam-instance-profile
  cloud_properties:
    iam_instance_profile: ((tas_blobstore_iam_instance_profile_name))
- name: pks-api-lb-security-groups
  cloud_properties:
    security_groups:
    - ((pks_api_lb_security_group_id))
    - ((platform_vms_security_group_id))
vmtypes-configuration:
  custom_only: true
  vm_types:
  - name: t3.nano
    cpu: 2
    ephemeral_disk: 8192
    ram: 512
    raw_instance_storage: false
  - name: t3.micro
    cpu: 2
    ephemeral_disk: 8192
    ram: 1024
    raw_instance_storage: false
  - name: t3.small
    cpu: 2
    ephemeral_disk: 8192
    ram: 2048
    raw_instance_storage: false
  - name: t3.medium
    cpu: 2
    ephemeral_disk: 32768
    ram: 4096
    raw_instance_storage: false
  - name: c5.large
    cpu: 2
    ephemeral_disk: 32768
    ram: 4096
    raw_instance_storage: false
  - name: c5.xlarge
    cpu: 4
    ephemeral_disk: 65536
    ram: 8192
    raw_instance_storage: false
  - name: c5.2xlarge
    cpu: 8
    ephemeral_disk: 131072
    ram: 16384
    raw_instance_storage: false
  - name: c5.4xlarge
    cpu: 16
    ephemeral_disk: 262144
    ram: 32768
    raw_instance_storage: false
  - name: c5.9xlarge
    cpu: 36
    ephemeral_disk: 524288
    ram: 73728
    raw_instance_storage: false
  - name: m5.large
    cpu: 2
    ephemeral_disk: 32768
    ram: 8192
    raw_instance_storage: false
  - name: m5.xlarge
    cpu: 4
    ephemeral_disk: 65536
    ram: 16384
    raw_instance_storage: false
  - name: m5.2xlarge
    cpu: 8
    ephemeral_disk: 131072
    ram: 32768
    raw_instance_storage: false
  - name: m5.4xlarge
    cpu: 16
    ephemeral_disk: 262144
    ram: 65536
    raw_instance_storage: false
  - name: m5.12xlarge
    cpu: 48
    ephemeral_disk: 1048576
    ram: 196608
    raw_instance_storage: false
  - name: r5.large
    cpu: 2
    ephemeral_disk: 65536
    ram: 16384
    raw_instance_storage: false
  - name: r5.xlarge
    cpu: 4
    ephemeral_disk: 131072
    ram: 32768
    raw_instance_storage: false
  - name: r5.2xlarge
    cpu: 8
    ephemeral_disk: 262144
    ram: 65536
    raw_instance_storage: false
  - name: r5.4xlarge
    cpu: 16
    ephemeral_disk: 524288
    ram: 131072
    raw_instance_storage: false
  - name: r5.12xlarge
    cpu: 48
    ephemeral_disk: 2097152
    ram: 393216
    raw_instance_storage: false
  - name: i3.8xlarge
    cpu: 32
    ephemeral_disk: 983040
    ram: 249856
    raw_instance_storage: true
  - name: d2.8xlarge
    cpu: 36
    ephemeral_disk: 983040
    ram: 249856
    raw_instance_storage: true